apiVersion: apps/v1 
kind: Deployment
metadata:
  name: products
  labels: 
     app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products

  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: 140598534703.dkr.ecr.us-east-1.amazonaws.com/ecr_obligatorio_develop:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1