apiVersion: apps/v1 
kind: Deployment
metadata:
  name: products
  labels: 
     app: products

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: products

  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
      #Parametrizar:
        image: 198937174082.dkr.ecr.us-east-1.amazonaws.com/products:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1