name: api products testing
on:
    push:
        branches: [ "main" , "staging" , "develop", "feature/*"]
    pull_request:
        branches: [ "main" , "staging" , "develop" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK Corretto 8
          uses: actions/setup-java@v4
          with:
            java-version: '8'
            distribution: 'corretto'
            cache: maven
        - name: Build and Test with Maven
          run: mvn -B package --file pom.xml
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag products-service-example:latest
        - name: Run the Docker container
          run: docker run -d -p 8080:8080 products-service-example:latest
        - name: Wait for the application to start
          run: |
            echo "Waiting for application to start..."
            sleep 30
        - name: Install Newman
          run: npm install -g newman
        - name: Run Newman tests
          run: newman run ./src/test/API_Products.postman_collection.json
        - name: Stop the Docker container
          run: docker stop $(docker ps -q --filter ancestor=products-service-example:latest)